expinfo:
  lore_size: 15
  gui:
    title: "<gradient:#562d1d:#4c243c>Bilgiler ➢ Sıralama ➣ <gradient:#ce1e92:#aa00ff>Tecrübeler"
    blank_material: MAGENTA_STAINED_GLASS_PANE
    jobitem:
      name: "<job>"
      lore:
        - " <primary><1actionandvalue> <secondary><1exp><gray><expsymbol> <primary><1money><gray><moneysymbol> "
        - " <primary><2actionandvalue> <secondary><2exp><gray><expsymbol> <primary><2money><gray><moneysymbol> "
        - " <primary><3actionandvalue> <secondary><3exp><gray><expsymbol> <primary><3money><gray><moneysymbol> "
        - " <primary><4actionandvalue> <secondary><4exp><gray><expsymbol> <primary><4money><gray><moneysymbol> "
        - " <primary><5actionandvalue> <secondary><5exp><gray><expsymbol> <primary><5money><gray><moneysymbol> "
        - " <primary><6actionandvalue> <secondary><6exp><gray><expsymbol> <primary><6money><gray><moneysymbol> "
        - " <primary><7actionandvalue> <secondary><7exp><gray><expsymbol> <primary><7money><gray><moneysymbol> "
        - " <primary><8actionandvalue> <secondary><8exp><gray><expsymbol> <primary><8money><gray><moneysymbol> "
        - " <primary><9actionandvalue> <secondary><9exp><gray><expsymbol> <primary><9money><gray><moneysymbol> "
        - " <primary><10actionandvalue> <secondary><10exp><gray><expsymbol> <primary><10money><gray><moneysymbol> "
        - " <primary><11actionandvalue> <secondary><11exp><gray><expsymbol> <primary><11money><gray><moneysymbol> "
        - " <primary><12actionandvalue> <secondary><12exp><gray><expsymbol> <primary><12money><gray><moneysymbol> "
        - " <primary><13actionandvalue> <secondary><13exp><gray><expsymbol> <primary><13money><gray><moneysymbol> "
        - " <primary><14actionandvalue> <secondary><14exp><gray><expsymbol> <primary><14money><gray><moneysymbol> "
        - " <primary><15actionandvalue> <secondary><15exp><gray><expsymbol> <primary><15money><gray><moneysymbol> "
        - ""
        - " <primary>SOL ↓ <dark_gray>| <secondary>SAĞ ↑ "
        - " <gold>ℹ <primary>SHIFT <gray>ile basmak 5'e katlar."
leaderboard:
  calculate_top: 100
  list_in_lore: 10
  gui:
    title: "<gradient:#562d1d:#51282d>Bilgiler ➢ <gradient:#e43050:#d32283>Sıralama ➣ <gradient:#4b243e:#431d56>Tecrübeler"
    blank_material: RED_STAINED_GLASS_PANE
    jobitem:
      name: "<job> <dark_gray>(<primary><min> <gray>ile <secondary><max><dark_gray>)"
      lore:
        - " <primary><bold><1>.</bold> <1displayname> <secondary><1level> <gray>seviye "
        - " <primary><bold><2>.</bold> <2displayname> <secondary><2level> <gray>seviye "
        - " <primary><bold><3>.</bold> <3displayname> <secondary><3level> <gray>seviye "
        - " <primary><bold><4>.</bold> <4displayname> <secondary><4level> <gray>seviye "
        - " <primary><bold><5>.</bold> <5displayname> <secondary><5level> <gray>seviye "
        - " <primary><bold><6>.</bold> <6displayname> <secondary><6level> <gray>seviye "
        - " <primary><bold><7>.</bold> <7displayname> <secondary><7level> <gray>seviye "
        - " <primary><bold><8>.</bold> <8displayname> <secondary><8level> <gray>seviye "
        - " <primary><bold><9>.</bold> <9displayname> <secondary><9level> <gray>seviye "
        - " <primary><bold><10>.</bold> <10displayname> <secondary><10level> <gray>seviye "
        - " <gray>Sen <primary><level> <gray>seviye ile <secondary><position>. <gray>sıradasın. "
        - ""
        - " <gold>⌚ <gray>Yenilenmeye kalan "
        - "  <secondary><time> "
        - ""
        - " <primary>SOL ↓ <dark_gray>| <secondary>SAĞ ↑ "
        - " <gold>ℹ <primary>SHIFT <gray>ile basmak 5'e katlar."
gui:
  change_page_cooldown: 40
  title: "<gradient:#FF4600:#e93442>Bilgiler <gradient:#51282d:#431d56>➢ Sıralama ➣ Tecrübeler"
  blank_material: ORANGE_STAINED_GLASS_PANE
  jobitem:
    name: "<job>"
    lore:
      - " <gradient:#6D6666:#938B8B:#777676><exp>/<next_exp> "
      - " <primary><level> <progress> <secondary><next_level> "
      - ""
      - " <job> <gray>yeteneğinde: "
      - "  <gray>sıralamada <primary><position><gray>. sıradasın. "
      - "  <gray>bugüne kadar <primary><total_money><money_symbol> <gray>kazanmışsın."
      - ""
      - " <gray>Sıralamaya gitmek için <primary>SOL <gray>tıkla. "
      - " <gray>Tecrübelere gitmek için <primary>SAĞ <gray>tıkla. "

command:
  name: "jobs"
  description: "main command for Jobs"
  aliases:
    - "job"
    - "ujob"
    - "ujobs"
    - "skill"
    - "skills"

messages:
  reload: "<green>reloaded!"
  page_turn:
    sound: item.book.page_turn
  leaderboard:
    take_lead:
      chat: "<displayname> <job> <gray>yeteneğinde <primary><level> <gray>seviyeye ulaşıp <secondary><bold>1.</bold><gray>'liği <opponentdisplayname> <gray>aldı."
      sound: entity.ravager.celebrate
    get_in_top_10:
      chat: "<displayname> <job> <gray>yeteneğinde <primary><level> <gray>seviyeye ulaşıp ilk <secondary><bold>10</bold><gray>'a girdi."
      sound: entity.vindicator.celebrate
    your_position_taken: "<displayname> <job> <gray>yeteneğinde <primary><level> <gray>seviyeye ulaşıp <secondary><bold><position>.</bold> <gray>sırayı senden aldı."
    take_someones_position:
      chat: "<opponentdisplayname> <job> <gray>yeteneğinde geçerek <secondary><bold><position>.</bold> <gray>sen oldun."
      sound: entity.pillager.celebrate

symbols:
  money: pp
  exp: xp

actions:
  kill: "<value> <gray>öldür"
  breed: "<value> <gray>çiftleştir"
  break: "<value> <gray>kır"
  tame: "<value> <gray>evcilleştir"
  fish: "<value> <gray>tut"
  enchant: "<value> <gray>büyü bas"
  anvil_enchant: "<value> <gray>ile örste büyü bas"
  lootgenerate: "<value> <gray>sandığı aç"
  raid: "<value> <gray>savun"
  craft: "<value> <gray>üret"
  trade: "<value> <gray>takası yap"

special_values:
  1: "1. Seviye"
  2: "2. Seviye"
  3: "3. Seviye"
  win: "Köy yağmasının tamamını"
  wave: "Köy yağması dalgası"
  desert_pyramid: "Çöl Tapınağı"
  abandoned_mineshaft: "Maden Ocağı"
  ancient_city: "Antik Şehir"
  ancient_city_ice_box: "Antik Şehir"
  bastion_bridge: "Burç Kalıntısı Köprüsü"
  bastion_other: "Burç Kalıntısı"
  bastion_treasure: "Burç Kalıntısı Hazinesi"
  buried_treasure: "Gömülü Hazine"
  end_city_treasure: "End Şehri"
  igloo_chest: "İglo"
  jungle_temple: "Orman Tapınağı"
  pillager_outpost: "Yağmacı Karakolu"
  ruined_portal: "Harabe Portal"
  shipwreck_map: "Gemi Kalıntısı Harita"
  shipwreck_supply: "Gemi Kalıntısı"
  shipwreck_treasure: "Gemi Kalıntısı Hazine"
  simple_dungeon: "Zindan"
  stronghold_corridor: "End Portalı Kalesi Koridoru"
  stronghold_crossing: "End Portalı Kalesi"
  stronghold_library: "End Portalı Kalesi Kütüphane"
  underwater_ruin_big: "Büyük Su Altı Harabesi"
  underwater_ruin_small: "Su Altı Harabesi"
  village_armorer: "Zırhcı Köylü"
  village_butcher: "Kasap Köylü"
  village_cartographer: "Haritacı Köylü"
  village_desert_house: "Çöl Köyü"
  village_fisher: "Balıkçı Köylü"
  village_fletcher: "Okçu Köylü"
  village_mason: "Taşçı Köylü"
  village_plains_house: "Kırsal Köyü"
  village_savanna_house: "Savana Köyü"
  village_shepherd: "Çoban Köylü"
  village_snowy_house: "Karlı Köy"
  village_taiga_house: "Ladin Köyü"
  village_tannery: "Deri Ustası Köylü"
  village_temple: "Rahip Köylü"
  village_toolsmith: "Alet Ustası Köylü"
  village_weaponsmith: "Silah Ustası Köylü"
  woodland_mansion: "Malikane"