expinfo:
  list_in_lore: 15
  gui:
    title: "<gradient:#562d1d:#4c243c>Bilgiler ➢ Sıralama ➣ <gradient:#ce1e92:#aa00ff>Tecrübeler"
    blank_material: MAGENTA_STAINED_GLASS_PANE
    jobitem:
      name: "<job>"
      lore:
        - " <primary><1_action_value> <secondary><1_exp><gray><symbol_exp> <primary><1_money><gray><symbol_money> "
        - " <primary><2_action_value> <secondary><2_exp><gray><symbol_exp> <primary><2_money><gray><symbol_money> "
        - " <primary><3_action_value> <secondary><3_exp><gray><symbol_exp> <primary><3_money><gray><symbol_money> "
        - " <primary><4_action_value> <secondary><4_exp><gray><symbol_exp> <primary><4_money><gray><symbol_money> "
        - " <primary><5_action_value> <secondary><5_exp><gray><symbol_exp> <primary><5_money><gray><symbol_money> "
        - " <primary><6_action_value> <secondary><6_exp><gray><symbol_exp> <primary><6_money><gray><symbol_money> "
        - " <primary><7_action_value> <secondary><7_exp><gray><symbol_exp> <primary><7_money><gray><symbol_money> "
        - " <primary><8_action_value> <secondary><8_exp><gray><symbol_exp> <primary><8_money><gray><symbol_money> "
        - " <primary><9_action_value> <secondary><9_exp><gray><symbol_exp> <primary><9_money><gray><symbol_money> "
        - " <primary><10_action_value> <secondary><10_exp><gray><symbol_exp> <primary><10_money><gray><symbol_money> "
        - " <primary><11_action_value> <secondary><11_exp><gray><symbol_exp> <primary><11_money><gray><symbol_money> "
        - " <primary><12_action_value> <secondary><12_exp><gray><symbol_exp> <primary><12_money><gray><symbol_money> "
        - " <primary><13_action_value> <secondary><13_exp><gray><symbol_exp> <primary><13_money><gray><symbol_money> "
        - " <primary><14_action_value> <secondary><14_exp><gray><symbol_exp> <primary><14_money><gray><symbol_money> "
        - " <primary><15_action_value> <secondary><15_exp><gray><symbol_exp> <primary><15_money><gray><symbol_money> "
        - ""
        - " <primary>SOL ↓ <dark_gray>| <secondary>SAĞ ↑ "
        - " <gold>ℹ <primary>SHIFT <gray>ile basmak 5'e katlar."
leaderboard:
  calculate_top: 100
  list_in_lore: 10
  gui:
    title: "<gradient:#562d1d:#51282d>Bilgiler ➢ <gradient:#e43050:#d32283>Sıralama ➣ <gradient:#4b243e:#431d56>Tecrübeler"
    blank_material: RED_STAINED_GLASS_PANE
    jobitem:
      name: "<job> <dark_gray>(<primary><min> <gray>ile <secondary><max><dark_gray>)"
      lore:
        - " <primary><bold><1_position>.</bold> <1_displayname> <secondary><1_level> <gray>seviye "
        - " <primary><bold><2_position>.</bold> <2_displayname> <secondary><2_level> <gray>seviye "
        - " <primary><bold><3_position>.</bold> <3_displayname> <secondary><3_level> <gray>seviye "
        - " <primary><bold><4_position>.</bold> <4_displayname> <secondary><4_level> <gray>seviye "
        - " <primary><bold><5_position>.</bold> <5_displayname> <secondary><5_level> <gray>seviye "
        - " <primary><bold><6_position>.</bold> <6_displayname> <secondary><6_level> <gray>seviye "
        - " <primary><bold><7_position>.</bold> <7_displayname> <secondary><7_level> <gray>seviye "
        - " <primary><bold><8_position>.</bold> <8_displayname> <secondary><8_level> <gray>seviye "
        - " <primary><bold><9_position>.</bold> <9_displayname> <secondary><9_level> <gray>seviye "
        - " <primary><bold><10_position>.</bold> <10_displayname> <secondary><10_level> <gray>seviye "
        - " <gray>Sen <primary><level> <gray>seviye ile <secondary><position>. <gray>sıradasın. "
        - ""
        - " <gold>⌚ <gray>Yenilenmeye kalan "
        - "  <secondary><time> "
        - ""
        - " <primary>SOL ↓ <dark_gray>| <secondary>SAĞ ↑ "
        - " <gold>ℹ <primary>SHIFT <gray>ile basmak 5'e katlar."
gui:
  change_page_cooldown: 40
  title: "<gradient:#FF4600:#e93442>Bilgiler <gradient:#51282d:#431d56>➢ Sıralama ➣ Tecrübeler"
  blank_material: ORANGE_STAINED_GLASS_PANE
  jobitem:
    name: "<job>"
    lore:
      - " <gradient:#6D6666:#938B8B:#777676><exp>/<next_exp> "
      - " <primary><level> <progress> <secondary><next_level> "
      - ""
      - " <job> <gray>yeteneğinde: "
      - "  <gray>sıralamada <primary><position><gray>. sıradasın. "
      - "  <gray>bugüne kadar <primary><total_money><money_symbol> <gray>kazanmışsın."
      - ""
      - " <gray>Sıralamaya gitmek için <primary>SOL <gray>tıkla. "
      - " <gray>Tecrübelere gitmek için <primary>SAĞ <gray>tıkla. "
  navigation:
    left:
      material: ARROW
      name: "<yellow><-"
    right:
      material: ARROW
      name: "<yellow>->"


command:
  name: "jobs"
  description: "main command for Jobs"
  aliases:
    - "job"
    - "ujob"
    - "ujobs"
    - "skill"
    - "skills"

messages:
  reload: "<green>reloaded!"
  page_turn:
    sound: item.book.page_turn
  leaderboard_take_lead:
      chat: "<displayname> <job> <gray>yeteneğinde <primary><level> <gray>seviyeye ulaşıp <secondary><bold>1.</bold><gray>'liği <opponentdisplayname> <gray>aldı."
      sound: entity.ravager.celebrate
  leaderboard_get_in_top_10:
      chat: "<displayname> <job> <gray>yeteneğinde <primary><level> <gray>seviyeye ulaşıp ilk <secondary><bold>10</bold><gray>'a girdi."
      sound: entity.vindicator.celebrate
  leaderboard_your_position_taken: "<displayname> <job> <gray>yeteneğinde <primary><level> <gray>seviyeye ulaşıp <secondary><bold><position>.</bold> <gray>sırayı senden aldı."
  leaderboard_take_someones_position:
      chat: "<opponent_displayname> <job> <gray>yeteneğinde geçerek <secondary><bold><position>.</bold> <gray>sen oldun."
      sound: entity.pillager.celebrate

symbols:
  money: pp
  exp: xp

actions:
  kill: "<value> <gray>öldür"
  breed: "<value> <gray>çiftleştir"
  break: "<value> <gray>kır"
  tame: "<value> <gray>evcilleştir"
  fish: "<value> <gray>tut"
  enchant: "<value> <gray>büyü bas"
  anvil_merge: "<value> <gray>ile örste büyü bas"
  generate_loot: "<value> <gray>sandığı aç"
  raid: "<value> <gray>savun"
  craft: "<value> <gray>üret"
  trade: "<value> <gray>takası yap"
  harvest: "<value> <gray>hasat et"
  smelt: "<value> <gray>pişir"

special_values:
  1: "1. Seviye"
  2: "2. Seviye"
  3: "3. Seviye"
  4: "4. Seviye"
  5: "5. Seviye"
  6: "6. Seviye"
  7: "7. Seviye"
  8: "8. Seviye"
  9: "9. Seviye"
  10: "10. Seviye"
  11: "11. Seviye"
  12: "12. Seviye"
  13: "13. Seviye"
  14: "14. Seviye"
  15: "15. Seviye"
  16: "16. Seviye"
  17: "17. Seviye"
  18: "18. Seviye"
  19: "19. Seviye"
  20: "20. Seviye"
  21: "21. Seviye"
  22: "22. Seviye"
  23: "23. Seviye"
  24: "24. Seviye"
  25: "25. Seviye"
  26: "26. Seviye"
  27: "27. Seviye"
  28: "28. Seviye"
  29: "29. Seviye"
  30: "30. Seviye"

  win: "Köy yağmasının tamamını"
  wave: "Köy yağması dalgası"

  desert_pyramid: "Çöl Tapınağı"
  abandoned_mineshaft: "Maden Ocağı"
  ancient_city: "Antik Şehir"
  ancient_city_ice_box: "Antik Şehir"
  bastion_bridge: "Burç Kalıntısı Köprüsü"
  bastion_other: "Burç Kalıntısı"
  bastion_treasure: "Burç Kalıntısı Hazinesi"
  buried_treasure: "Gömülü Hazine"
  end_city_treasure: "End Şehri"
  igloo_chest: "İglo"
  jungle_temple: "Orman Tapınağı"
  pillager_outpost: "Yağmacı Karakolu"
  ruined_portal: "Harabe Portal"
  shipwreck_map: "Gemi Kalıntısı Harita"
  shipwreck_supply: "Gemi Kalıntısı"
  shipwreck_treasure: "Gemi Kalıntısı Hazine"
  simple_dungeon: "Zindan"
  stronghold_corridor: "End Portalı Kalesi Koridoru"
  stronghold_crossing: "End Portalı Kalesi"
  stronghold_library: "End Portalı Kalesi Kütüphane"
  underwater_ruin_big: "Büyük Su Altı Harabesi"
  underwater_ruin_small: "Su Altı Harabesi"
  village/village_armorer: "Zırhcı Köylü"
  village/village_butcher: "Kasap Köylü"
  village/village_cartographer: "Haritacı Köylü"
  village/village_desert_house: "Çöl Köyü"
  village/village_fisher: "Balıkçı Köylü"
  village/village_fletcher: "Okçu Köylü"
  village/village_mason: "Taşçı Köylü"
  village/village_plains_house: "Kırsal Köyü"
  village/village_savanna_house: "Savana Köyü"
  village/village_shepherd: "Çoban Köylü"
  village/village_snowy_house: "Karlı Köy"
  village/village_taiga_house: "Ladin Köyü"
  village/village_tannery: "Deri Ustası Köylü"
  village/village_temple: "Rahip Köylü"
  village/village_toolsmith: "Alet Ustası Köylü"
  village/village_weaponsmith: "Silah Ustası Köylü"
  woodland_mansion: "Malikane"
  bastion_hoglin_stable: "Burç Kalıntısı Domuz Ahırı"
  jungle_temple_dispenser: "Orman Tapınağı Fırlatıcı"
  nether_bridge: "Nether Köprüsü"
  trial_chambers/corridor: "Sınama Odası Koridoru"
  trial_chambers/entrance: "Sınama Odası Girişi"
  trial_chambers/intersection: "Sınama Odası Birleşim Yeri"
  trial_chambers/intersection_barrel: "Sınama Odası Birleşim Yeri Varili"
  trial_chambers/reward: "Sınama Odası Ödülü"
  trial_chambers/reward_common: "Sınama Odası Yaygın Ödülü"
  trial_chambers/reward_ominous: "Sınama Odası Korkutucu Ödülü"
  trial_chambers/reward_ominous_common: "Sınama Odası Korkutucu Yaygın Ödülü"
  trial_chambers/reward_ominous_rare: "Sınama Odası Korkutucu Nadir Ödülü"
  trial_chambers/reward_ominous_unique: "Sınama Odası Korkutucu Eşsiz Ödülü"
  trial_chambers/reward_rare: "Sınama Odası Nadir Ödülü"
  trial_chambers/reward_unique: "Sınama Odası Eşsiz Ödülü"
  trial_chambers/supply: "Sınama Odası Kaynak"