name: UJobs
version: '1.0.0'
main: me.usainsrht.ujobs.UJobs
api-version: '1.21'
authors: [ UsainSrht ]
dependencies:
  server:
    Vault:
      required: true
      load: BEFORE
      join-classpath: true